require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
AllCops:
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
# Gemspec/DeprecatedAttributeAssignment:
#   Enabled: true
Gemspec/RequireMFA:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: false
Layout/SpaceBeforeBrackets:
  Enabled: false
Lint/AmbiguousAssignment:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/AmbiguousRange:
  Enabled: false
Lint/DeprecatedConstants:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
Lint/EmptyInPattern:
  Enabled: false
